#!/usr/bin/env python

"""

	gcp
	GDataCopier, http://gdatacopier.googlecode.com/

	Copyright 2009 Eternity Technologies.
	Distributed under the terms and conditions of the GNU/GPL v3
	
	Version 2.0
	
	Requires:
		
		- Python 2.5
		- Python GData API 1.3+
		
"""

try:
	import gdata.service
	import gdata.auth
except:
	print "Error"
	exit(0)

class GLS:
	
	def __init__(self):
		return
		
	def greet_user(self):
		return
		
	def parse_user_options(self):
		return
		
	def run(self):
		return


if __name__ == "__main__":
	gls = GLS()
	gls.run()