.TH "src/gdatacopier/auth.py" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gdatacopier/auth.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgdatacopier::auth::KeyRingProxy\fP"
.br
.RI "\fIProvides a Proxy to the local Keychain service via Python's Keyring package\&. \fP"
.ti -1c
.RI "class \fBgdatacopier::auth::Provider\fP"
.br
.RI "\fIProvides a Wrapper for OAuth 2 authentication against Google APIs\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgdatacopier::auth\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBgdatacopier::auth::__all__\fP = ['Provider']"
.br
.ti -1c
.RI "string \fBgdatacopier::auth::__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fBgdatacopier::auth::__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
