.TH "gdatacopier::ux::GDocEntry" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::ux::GDocEntry \- 
.PP
Represents a single Docs Entry, abstracts properties required by GDataCopier\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBtitle\fP"
.br
.ti -1c
.RI "def \fBdocument_type\fP"
.br
.ti -1c
.RI "def \fBdate_string\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a single Docs Entry, abstracts properties required by GDataCopier\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def \fBgdatacopier::ux::GDocEntry::__init__\fP (self, resource)"
.SH "Member Function Documentation"
.PP 
.SS "def \fBgdatacopier::ux::GDocEntry::date_string\fP (self)"
.SS "def \fBgdatacopier::ux::GDocEntry::document_type\fP (self)"
.SS "def \fBgdatacopier::ux::GDocEntry::title\fP (self)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
