#!/usr/bin/env python

"""

	gcp
	GDataCopier, http://gdatacopier.googlecode.com/
	
	Copyright 2009 Eternity Technologies.
	Distributed under the terms and conditions of the GNU/GPL v3
	
	Version 2.0
	
	Requires:
		
		- Python 2.5
		- Python GData API 1.3+
		
	Summary:
		
	GDataCopier originally started as a backup utility for Google Documents.
	When first published GData API didn't allow downloading documents, GDataCopier
	pretended to Firefox and perform the interactions required to download the
	documents.
	
	Since GData 1.3 Google has incorporated downloading documents into the API.
	As of Version 2.0 GDataCopier provides a cp like command line utility to ease
	backup of Google Documents simpler for System Administrators.

	Usage:
	
	gcp --[options] username@domain.com:/[doctype]/* /home/devraj
	
	doctype:
	
	docs			for documents
	sheets			for spreadsheets
	slides			for presentations
	
	Options:
	
	--metadata		Exports a meta information for each download
	--password=		Option to provide password on the command line
	--log=			Asks gcp to write to syslog	
	--format=		pdf, doc, oo (default), txt, xls
	
"""



def main():
	return
	
if __name__ == "__main__":
	main()