#!/bin/env python

"""

	gdoc-cp
	GDataCopier, http://gdatacopier.googlecode.com/
	
	Copyright 2009 Eternity Technologies.
	Distributed under the terms and conditions of the GNU/GPL v3
	
	Version 2.0
	
	Requires:
		
		- Python 2.5
		- Python GData API 1.3+
		
	Summary:
		
	GDataCopier originally started as a backup utility for Google Documents.
	When first published GData API didn't allow downloading documents, GDataCopier
	pretended to Firefox and perform the interactions required to download the
	documents.
	
	Since GData 1.3 Google has incorporated downloading documents into the API.
	As of Version 2.0 GDataCopier provides a cp like command line utility to ease
	backup of Google Documents simpler for System Administrators.
	

"""



def main():
	return
	
if __name__ == "__main__":
	main()