.TH "gdatacopier" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBauth\fP"
.br
.ti -1c
.RI "namespace \fBux\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOAuthCredentials\fP"
.br
.ti -1c
.RI "class \fBParserBuilder\fP"
.br
.RI "\fISets up the Argparser for GDataCopier\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB__all__\fP = ['auth', 'ux']"
.br
.ti -1c
.RI "string \fB__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fB__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list \fBgdatacopier::__all__\fP = ['auth', 'ux']"
.SS "string \fBgdatacopier::__author__\fP = 'devraj (Devraj Mukherjee)'"
.SS "string \fBgdatacopier::__version__\fP = '3\&.0'"
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
