.TH "gdatacopier::ux" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::ux \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGDocEntry\fP"
.br
.RI "\fIRepresents a single Docs Entry, abstracts properties required by GDataCopier\&. \fP"
.ti -1c
.RI "class \fBGDocClientProxy\fP"
.br
.RI "\fIProxy client that encapsulates the use of GData Client\&. \fP"
.ti -1c
.RI "class \fBHandler\fP"
.br
.RI "\fIWrapper to encapsulate the user experience\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB__all__\fP = ['\fBHandler\fP']"
.br
.ti -1c
.RI "string \fB__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fB__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list \fBgdatacopier::ux::__all__\fP = ['\fBHandler\fP']"
.SS "string \fBgdatacopier::ux::__author__\fP = 'devraj (Devraj Mukherjee)'"
.SS "string \fBgdatacopier::ux::__version__\fP = '3\&.0'"
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
