.TH "gdatacopier::ParserBuilder" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::ParserBuilder \- 
.PP
Sets up the Argparser for GDataCopier\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetup_mkdir_subparser\fP"
.br
.RI "\fISets up a Subparser for the logout command\&. \fP"
.ti -1c
.RI "def \fBsetup_delete_subparser\fP"
.br
.RI "\fISets up a Subparser for the logout command\&. \fP"
.ti -1c
.RI "def \fBsetup_list_subparser\fP"
.br
.RI "\fISets up a Subparser for the logout command\&. \fP"
.ti -1c
.RI "def \fBsetup_copy_subparser\fP"
.br
.RI "\fISets up a Subparser for the logout command\&. \fP"
.ti -1c
.RI "def \fBsetup_logout_subparser\fP"
.br
.RI "\fISets up a Subparser for the logout command\&. \fP"
.ti -1c
.RI "def \fBsetup_login_subparser\fP"
.br
.RI "\fISets up a Subparser for the login command\&. \fP"
.ti -1c
.RI "def \fBsetup_args_parser\fP"
.br
.RI "\fISets up the ArgParser and command line rules\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Sets up the Argparser for GDataCopier\&. 
.SH "Member Function Documentation"
.PP 
.SS "def \fBgdatacopier::ParserBuilder::setup_args_parser\fP (self)"
.PP
Sets up the ArgParser and command line rules\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_copy_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the logout command\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_delete_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the logout command\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_list_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the logout command\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_login_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the login command\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_logout_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the logout command\&. 
.SS "def \fBgdatacopier::ParserBuilder::setup_mkdir_subparser\fP (self, subparsers)"
.PP
Sets up a Subparser for the logout command\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
