.TH "gdatacopier::auth" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::auth \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeyRingProxy\fP"
.br
.RI "\fIProvides a Proxy to the local Keychain service via Python's Keyring package\&. \fP"
.ti -1c
.RI "class \fBProvider\fP"
.br
.RI "\fIProvides a Wrapper for OAuth 2 authentication against Google APIs\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fB__all__\fP = ['\fBProvider\fP']"
.br
.ti -1c
.RI "string \fB__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fB__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list \fBgdatacopier::auth::__all__\fP = ['\fBProvider\fP']"
.SS "string \fBgdatacopier::auth::__author__\fP = 'devraj (Devraj Mukherjee)'"
.SS "string \fBgdatacopier::auth::__version__\fP = '3\&.0'"
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
