.TH "gdatacopier::ux::Handler" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::ux::Handler \- 
.PP
Wrapper to encapsulate the user experience\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBlogin\fP"
.br
.RI "\fIAttemptes to perform OAuth 2\&.0 login\&. \fP"
.ti -1c
.RI "def \fBlogout\fP"
.br
.RI "\fIRevokes a OAuth token if available\&. \fP"
.ti -1c
.RI "def \fBlist\fP"
.br
.RI "\fILists filtered list of documents on Google servers\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Wrapper to encapsulate the user experience\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "def \fBgdatacopier::ux::Handler::__init__\fP (self, args)"
.SH "Member Function Documentation"
.PP 
.SS "def \fBgdatacopier::ux::Handler::list\fP (self)"
.PP
Lists filtered list of documents on Google servers\&. 
.SS "def \fBgdatacopier::ux::Handler::login\fP (self)"
.PP
Attemptes to perform OAuth 2\&.0 login\&. If the user has an accessible browser the webbrowser package will attempt to automatically redirect them to the URL, on headless machiens the user is excepected to copy and paste the prompted URL into a browser\&.
.PP
Once the authenticaiton is complete, the user is expected to hit enter to allow GDataCopier to complete the authentcation process\&. 
.SS "def \fBgdatacopier::ux::Handler::logout\fP (self)"
.PP
Revokes a OAuth token if available\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
