.TH "src/gdatacopier/ux.py" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gdatacopier/ux.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgdatacopier::ux::GDocEntry\fP"
.br
.RI "\fIRepresents a single Docs Entry, abstracts properties required by GDataCopier\&. \fP"
.ti -1c
.RI "class \fBgdatacopier::ux::GDocClientProxy\fP"
.br
.RI "\fIProxy client that encapsulates the use of GData Client\&. \fP"
.ti -1c
.RI "class \fBgdatacopier::ux::Handler\fP"
.br
.RI "\fIWrapper to encapsulate the user experience\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgdatacopier::ux\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBgdatacopier::ux::__all__\fP = ['Handler']"
.br
.ti -1c
.RI "string \fBgdatacopier::ux::__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fBgdatacopier::ux::__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
