.TH "src/gdatacopier/__init__.py" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/gdatacopier/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBgdatacopier::OAuthCredentials\fP"
.br
.ti -1c
.RI "class \fBgdatacopier::ParserBuilder\fP"
.br
.RI "\fISets up the Argparser for GDataCopier\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBgdatacopier\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBgdatacopier::__all__\fP = ['auth', 'ux']"
.br
.ti -1c
.RI "string \fBgdatacopier::__author__\fP = 'devraj (Devraj Mukherjee)'"
.br
.ti -1c
.RI "string \fBgdatacopier::__version__\fP = '3\&.0'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
