.TH "gdatacopier::OAuthCredentials" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::OAuthCredentials \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "string \fBUSER_AGENT\fP = 'GDataCopier-v3'"
.br
.ti -1c
.RI "string \fBCLIENT_ID\fP = '351782124357\&.apps\&.googleusercontent\&.com'"
.br
.ti -1c
.RI "string \fBCLIENT_SECRET\fP = 'xC3varEAS9pq--71p22oFoye'"
.br
.ti -1c
.RI "list \fBSCOPE\fP = ['https://docs\&.google\&.com/feeds/']"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "string \fBgdatacopier::OAuthCredentials::CLIENT_ID\fP = '351782124357\&.apps\&.googleusercontent\&.com'\fC [static]\fP"
.SS "string \fBgdatacopier::OAuthCredentials::CLIENT_SECRET\fP = 'xC3varEAS9pq--71p22oFoye'\fC [static]\fP"
.SS "list \fBgdatacopier::OAuthCredentials::SCOPE\fP = ['https://docs\&.google\&.com/feeds/']\fC [static]\fP"
.SS "string \fBgdatacopier::OAuthCredentials::USER_AGENT\fP = 'GDataCopier-v3'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
