.TH "gdatacopier::auth::KeyRingProxy" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::auth::KeyRingProxy \- 
.PP
Provides a Proxy to the local Keychain service via Python's Keyring package\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBtoken\fP"
.br
.ti -1c
.RI "def \fBtoken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a Proxy to the local Keychain service via Python's Keyring package\&. 

\fBKeyRingProxy\fP is used by the auth provider to store the OAuth 2 token, it can be used to securely store any other properties that GDatacopier might require\&.
.PP
Python keyring support is provided by http://pypi.python.org/pypi/keyring
.PP
available via pip or easy_install 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def \fBgdatacopier::auth::KeyRingProxy::__init__\fP (self)"
.SH "Member Function Documentation"
.PP 
.SS "def \fBgdatacopier::auth::KeyRingProxy::token\fP (self)"
.SS "def \fBgdatacopier::auth::KeyRingProxy::token\fP (self, value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
