.TH "gdatacopier::ux::GDocClientProxy" 3 "Sun Apr 8 2012" "Version 3" "GDataCopier" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdatacopier::ux::GDocClientProxy \- 
.PP
Proxy client that encapsulates the use of GData Client\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBauthorize\fP"
.br
.ti -1c
.RI "def \fBget_docs_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Proxy client that encapsulates the use of GData Client\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def \fBgdatacopier::ux::GDocClientProxy::__init__\fP (self, auth_provider)"
.SH "Member Function Documentation"
.PP 
.SS "def \fBgdatacopier::ux::GDocClientProxy::authorize\fP (self)"
.SS "def \fBgdatacopier::ux::GDocClientProxy::get_docs_list\fP (self, owner_filter = \fCNone\fP, title_filter = \fCNone\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for GDataCopier from the source code\&.
